[project]
name = 'LightningStacks'
description = ''
authors = []
telemetry = true
cache_dir = './.cache'
requirements = []
[contracts.lightning-payment-channel]
path = 'contracts/lightning-payment-channel.clar'
clarity_version = 3
epoch = 3.1
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
